<script lang="ts">
  import PublicShell from '$lib/components/PublicShell.svelte';
  import ContentGrid from '$lib/components/ContentGrid.svelte';
  let { data }: { data: import('./$types').PageData } = $props();
  let hero = $derived(data.homepage.hero ?? {});
  let heroImage = $derived(hero.media_id ? `/media/${hero.media_id}` : '/assets/hero-construction.png');
  let heroAlt = $derived(hero.media_alt || 'Dokumentasi pekerjaan Jasa Perbaikan Bandung');
</script>

<svelte:head>
  <title>Jasa Perbaikan & Renovasi Bandung | Jasa Perbaikan Bandung</title>
  <meta name="description" content="Jasa perbaikan, renovasi, arsitektur, interior, dan eksterior untuk rumah serta tempat usaha di Bandung." />
  <link rel="canonical" href="/" />
</svelte:head>

<PublicShell>
  <main id="content">
    <section class="page-shell grid gap-10 py-12 sm:py-16 lg:min-h-[44rem] lg:grid-cols-[1.08fr_0.92fr] lg:items-center lg:py-20">
      <div class="max-w-3xl"><p class="eyebrow motion-enter mb-6 text-clay">{hero.eyebrow || 'Jasa Perbaikan, Arsitektur, Interior, dan Renovasi'}</p><h1 class="page-title motion-enter motion-enter-delay">{hero.heading || 'Perbaikan & renovasi di Bandung.'}</h1><p class="motion-enter motion-enter-delay mt-8 max-w-2xl text-lg leading-8 text-forest">{hero.body || 'Jasa Perbaikan Bandung membantu perbaikan, renovasi, pekerjaan arsitektur, serta penataan interior dan eksterior untuk rumah dan tempat usaha di Bandung dan sekitarnya.'}</p><div class="motion-enter motion-enter-delay-2 mt-10 flex flex-wrap gap-3"><a class="button-primary" href={hero.cta_href || '/kontak'}>{hero.cta_label || 'Konsultasi gratis'} <span aria-hidden="true">↗</span></a><a class="button-secondary" href="/portofolio">Lihat portofolio</a></div><ul class="motion-enter motion-enter-delay-2 mt-7 flex flex-wrap gap-x-4 gap-y-2 text-sm font-bold text-forest" aria-label="Komitmen layanan"><li>Tanpa biaya konsultasi awal</li><li aria-hidden="true">•</li><li>Penawaran transparan</li><li aria-hidden="true">•</li><li>Bandung & sekitarnya</li></ul></div>
      <figure class={`motion-enter motion-enter-delay relative overflow-hidden bg-ink ${hero.media_id ? 'aspect-[4/3]' : ''}`}><img class={`w-full transition-transform duration-700 ease-[var(--ease-out-expo)] hover:scale-[1.025] ${hero.media_id ? 'h-full object-contain' : 'h-80 object-cover sm:h-[34rem] lg:h-[38rem]'}`} src={heroImage} alt={heroAlt} /><p class="absolute left-4 top-4 border border-white/30 bg-ink/90 px-3 py-2 text-xs font-bold uppercase tracking-[0.1em] text-white">Bandung & sekitarnya</p><figcaption class="absolute bottom-0 left-0 max-w-xs bg-ink px-5 py-4 text-sm leading-6 text-white/80">Dari perbaikan terarah sampai renovasi menyeluruh untuk ruang tinggal dan usaha.</figcaption></figure>
    </section>
    <section class="border-y border-stone bg-mist"><div class="page-shell grid gap-8 py-12 md:grid-cols-[0.75fr_1.25fr] md:items-center"><p class="text-lg font-bold">Apa yang kami kerjakan</p><p class="max-w-4xl text-[clamp(1.45rem,3vw,2.25rem)] leading-[1.15] tracking-[-0.02em] text-forest">Perbaikan dan renovasi ruang, utilitas dan sistem keamanan, pengerjaan material, interior serta reparasi berbagai furniture kayu, hingga identitas visual bisnis.</p></div></section>
    <section id="layanan" class="page-shell py-16 sm:py-20 lg:py-28"><div class="mb-12 grid gap-6 lg:grid-cols-[0.65fr_1.35fr]"><p class="eyebrow text-clay">Layanan kami</p><div><h2 class="section-title">Dari perbaikan kecil sampai pengerjaan yang lebih menyeluruh.</h2><p class="mt-5 max-w-2xl leading-7 text-forest">Didukung tenaga ahli berpengalaman, pengerjaan rapi, dan komitmen pada ketepatan waktu dengan biaya yang transparan.</p></div></div><ContentGrid items={data.services} emptyTitle="Layanan sedang disiapkan" emptyBody="Ceritakan kebutuhan Anda agar kami dapat mengarahkan layanan yang relevan." /></section>
    <section id="cara-kerja" class="bg-ink text-white"><div class="page-shell grid gap-10 py-16 sm:py-20 lg:grid-cols-[0.75fr_1.25fr] lg:py-24"><div><p class="eyebrow text-clay">Cara kerja kami</p><h2 class="mt-5 font-display text-[clamp(2.25rem,4vw,4.25rem)] font-bold leading-[1] tracking-[-0.03em] text-balance">Keputusan yang jelas sebelum pekerjaan dimulai.</h2></div><ol class="divide-y divide-white/20 border-y border-white/20"><li class="grid grid-cols-[3rem_1fr] gap-4 py-6 transition-colors duration-300 hover:bg-white/5"><span class="font-bold text-clay">01</span><div><h3 class="font-bold">Konsultasi & konteks</h3><p class="mt-2 text-white/70">Kebutuhan, lokasi, batasan, dan target dibahas lebih dulu.</p></div></li><li class="grid grid-cols-[3rem_1fr] gap-4 py-6 transition-colors duration-300 hover:bg-white/5"><span class="font-bold text-clay">02</span><div><h3 class="font-bold">Survey & arah kerja</h3><p class="mt-2 text-white/70">Ruang, tahapan, serta titik keputusan dipetakan secara realistis.</p></div></li><li class="grid grid-cols-[3rem_1fr] gap-4 py-6 transition-colors duration-300 hover:bg-white/5"><span class="font-bold text-clay">03</span><div><h3 class="font-bold">Pengerjaan & pembaruan</h3><p class="mt-2 text-white/70">Eksekusi dijalankan dengan komunikasi berkala hingga serah terima.</p></div></li></ol></div></section>
    <section class="page-shell py-16 sm:py-20 lg:py-28"><div class="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p class="eyebrow text-clay">Portofolio Kami</p><h2 class="section-title mt-5">Dokumentasi hasil dari setiap kelompok layanan pekerjaan.</h2></div><a class="text-link" href="/portofolio">Lihat semua portofolio ↗</a></div><ContentGrid items={data.projects} emptyTitle="Portofolio sedang disiapkan" emptyBody="Dokumentasi pekerjaan akan ditampilkan bersama konteks yang dapat dipertanggungjawabkan." /></section>
    <section class="bg-spruce text-white"><div class="page-shell grid gap-8 py-14 sm:py-16 md:grid-cols-[1fr_auto] md:items-end"><div><p class="eyebrow text-white/70">Mulai dari percakapan awal</p><h2 class="mt-4 max-w-3xl font-display text-[clamp(2.25rem,4vw,4rem)] font-bold leading-[1] tracking-[-0.03em] text-balance">Ceritakan ruang yang ingin Anda siapkan.</h2></div><a class="button-primary bg-white text-ink hover:bg-mist" href="/kontak">Konsultasikan proyek</a></div></section>
  </main>
</PublicShell>
