INSERT INTO page_content (key, status, active, data)
VALUES (
  'hero',
  'PUBLISHED',
  1,
  '{"eyebrow":"Jasa Perbaikan, Pekerjaan Arsitektur, Interior, dan Renovasi","heading":"Solusi terpercaya untuk rumah dan tempat usaha Anda di Bandung.","body":"HD Karya Bandung membantu perbaikan, renovasi, pekerjaan arsitektur, serta penataan interior dan eksterior untuk rumah dan tempat usaha di Bandung dan sekitarnya.","cta_label":"Konsultasi gratis","cta_href":"/kontak"}'
)
ON CONFLICT(key) DO UPDATE SET status = excluded.status, active = excluded.active, data = excluded.data, updated_at = CURRENT_TIMESTAMP;

INSERT INTO content_items (id, kind, title, slug, category, status, featured, summary, body, data, seo_title, meta_description, index_status, published_at)
VALUES
  ('profile-0001', 'LAYANAN', 'Jasa Perbaikan Rumah/Kantor', 'perbaikan-rumah-kantor', 'Perbaikan & renovasi', 'PUBLISHED', 1, 'Penanganan cepat untuk atap bocor, dinding retak, dan perbaikan struktur ringan.', 'Penanganan cepat dan tepat untuk berbagai kerusakan bangunan, mulai dari atap bocor, dinding retak, hingga perbaikan struktur ringan agar properti tetap aman dan nyaman.', '{"suitable_for":"Hunian, kantor, dan tempat usaha","scope":"Atap bocor; dinding retak; perbaikan struktur ringan"}', 'Jasa Perbaikan Rumah & Kantor Bandung | HD Karya', 'Perbaikan atap bocor, dinding retak, dan struktur ringan untuk rumah atau kantor di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0002', 'LAYANAN', 'Jasa Renovasi & Pengecatan Ulang', 'renovasi-pengecatan-ulang', 'Perbaikan & renovasi', 'PUBLISHED', 1, 'Renovasi tata ruang dan pengecatan rapi untuk hunian atau kantor.', 'Ubah tampilan hunian atau kantor menjadi lebih segar, modern, dan bernilai melalui renovasi tata ruang serta pengecatan rapi berkualitas tahan lama.', '{"suitable_for":"Hunian, kantor, dan tempat usaha","scope":"Renovasi tata ruang; pengecatan ulang"}', 'Jasa Renovasi & Pengecatan Bandung | HD Karya', 'Renovasi tata ruang dan pengecatan ulang untuk hunian atau kantor di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0003', 'LAYANAN', 'Jasa Perbaikan Lemari Kayu', 'perbaikan-lemari-kayu', 'Interior & restorasi kayu', 'PUBLISHED', 0, 'Restorasi lemari kayu yang rusak, lapuk, atau terkena rayap.', 'Restorasi dan perbaikan lemari kayu yang rusak, lapuk, atau terkena rayap agar kembali kokoh, fungsional, dan tampak seperti baru.', '{"suitable_for":"Lemari kayu pada hunian dan ruang usaha","scope":"Restorasi; perbaikan kerusakan; penanganan rayap"}', 'Jasa Perbaikan Lemari Kayu Bandung | HD Karya', 'Restorasi lemari kayu rusak, lapuk, atau terkena rayap di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0004', 'LAYANAN', 'Jasa Instalasi/Relokasi Listrik', 'instalasi-relokasi-listrik', 'Utilitas & sistem keamanan', 'PUBLISHED', 1, 'Pemasangan jalur baru, titik sakelar, stopkontak, dan relokasi listrik.', 'Layanan kelistrikan profesional untuk pemasangan jalur baru, penambahan titik sakelar atau stopkontak, hingga pemindahan tata letak listrik yang aman dan sesuai standar keselamatan.', '{"suitable_for":"Hunian, kantor, dan tempat usaha","scope":"Jalur listrik baru; titik sakelar; stopkontak; relokasi listrik"}', 'Jasa Instalasi Listrik Bandung | HD Karya', 'Instalasi dan relokasi listrik untuk rumah, kantor, dan tempat usaha di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0005', 'LAYANAN', 'Jasa Instalasi AC & CCTV', 'instalasi-ac-cctv', 'Utilitas & sistem keamanan', 'PUBLISHED', 1, 'Pemasangan AC dan sistem CCTV untuk kenyamanan serta keamanan ruang.', 'Pemasangan unit AC untuk kenyamanan ruangan serta instalasi sistem CCTV modern untuk meningkatkan keamanan rumah dan tempat usaha secara optimal.', '{"suitable_for":"Rumah dan tempat usaha","scope":"Instalasi AC; instalasi CCTV"}', 'Jasa Instalasi AC & CCTV Bandung | HD Karya', 'Pemasangan AC dan CCTV untuk rumah atau tempat usaha di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0006', 'LAYANAN', 'Pengerjaan Kusen Aluminium', 'kusen-aluminium', 'Spesialisasi material struktural', 'PUBLISHED', 0, 'Pembuatan kusen, pintu, dan jendela aluminium yang modern dan tahan cuaca.', 'Pembuatan dan pemasangan kusen, pintu, serta jendela aluminium yang modern, anti-rayap, tahan cuaca, dan memberikan kesan elegan pada bangunan.', '{"suitable_for":"Hunian, kantor, dan tempat usaha","scope":"Kusen aluminium; pintu; jendela"}', 'Jasa Kusen Aluminium Bandung | HD Karya', 'Pembuatan dan pemasangan kusen aluminium, pintu, serta jendela di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0007', 'LAYANAN', 'Pengerjaan Kaca Tempered', 'kaca-tempered', 'Spesialisasi material struktural', 'PUBLISHED', 0, 'Aplikasi kaca tempered untuk railing, kanopi, pintu toko, dan partisi kamar mandi.', 'Aplikasi kaca tempered ekstra kuat dan aman untuk railing tangga, kanopi, pintu kaca toko, hingga partisi kamar mandi berdesain mewah.', '{"suitable_for":"Hunian dan ruang usaha","scope":"Railing tangga; kanopi; pintu kaca toko; partisi kamar mandi"}', 'Jasa Kaca Tempered Bandung | HD Karya', 'Aplikasi kaca tempered untuk railing, kanopi, pintu toko, dan partisi kamar mandi di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0008', 'LAYANAN', 'Pengerjaan Huruf Timbul & Neonbox', 'huruf-timbul-neonbox', 'Identitas visual bisnis', 'PUBLISHED', 0, 'Huruf timbul dan neonbox untuk meningkatkan citra bisnis melalui media promosi fisik.', 'Tingkatkan citra bisnis dengan media promosi fisik yang menarik, mulai dari huruf timbul berbahan akrilik atau stainless hingga neonbox terang yang memikat perhatian.', '{"suitable_for":"Tempat usaha","scope":"Huruf timbul akrilik; huruf timbul stainless; neonbox"}', 'Huruf Timbul & Neonbox Bandung | HD Karya', 'Pembuatan huruf timbul akrilik atau stainless dan neonbox untuk bisnis di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0009', 'LAYANAN', 'Pengerjaan Stainless Steel & Besi', 'stainless-steel-besi', 'Spesialisasi material struktural', 'PUBLISHED', 0, 'Pembuatan pagar, kanopi, railing balkon, dan teralis yang rapi serta tahan korosi.', 'Pembuatan pagar, kanopi, railing balkon, dan teralis dari bahan besi atau stainless steel berkualitas tinggi yang kokoh, rapi, dan tahan korosi.', '{"suitable_for":"Hunian dan tempat usaha","scope":"Pagar; kanopi; railing balkon; teralis"}', 'Jasa Pagar, Kanopi & Railing Bandung | HD Karya', 'Pembuatan pagar, kanopi, railing balkon, dan teralis besi atau stainless di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0010', 'LAYANAN', 'Pengerjaan Furniture & Interior', 'furniture-interior', 'Interior & restorasi kayu', 'PUBLISHED', 1, 'Furniture custom yang disesuaikan dengan konsep interior dan ukuran ruang.', 'Pembuatan custom furniture seperti kitchen set, backdrop TV, lemari, dan meja yang disesuaikan dengan konsep interior serta ukuran ruangan.', '{"suitable_for":"Hunian, kantor, dan tempat usaha","scope":"Kitchen set; backdrop TV; lemari; meja"}', 'Furniture Custom & Interior Bandung | HD Karya', 'Pembuatan furniture custom dan interior sesuai konsep serta ukuran ruang di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP),
  ('profile-0011', 'LAYANAN', 'Pengerjaan Kaca Grafir, Etsa, dan Inlay', 'kaca-grafir-etsa-inlay', 'Spesialisasi material struktural', 'PUBLISHED', 0, 'Dekorasi kaca bermotif artistik untuk nilai estetika dan kesan eksklusif.', 'Sentuhan seni pada dekorasi kaca dengan motif artistik untuk memberikan nilai estetika, kemewahan, dan kesan eksklusif pada ruangan.', '{"suitable_for":"Hunian, kantor, dan tempat usaha","scope":"Kaca grafir; etsa; inlay"}', 'Jasa Kaca Grafir, Etsa & Inlay Bandung | HD Karya', 'Pengerjaan kaca grafir, etsa, dan inlay untuk dekorasi ruang di Bandung.', 'INDEX_FOLLOW', CURRENT_TIMESTAMP)
ON CONFLICT(kind, slug) DO UPDATE SET
  title = excluded.title,
  category = excluded.category,
  status = excluded.status,
  featured = excluded.featured,
  summary = excluded.summary,
  body = excluded.body,
  data = excluded.data,
  seo_title = excluded.seo_title,
  meta_description = excluded.meta_description,
  index_status = excluded.index_status,
  published_at = excluded.published_at,
  updated_at = CURRENT_TIMESTAMP;
