import { fail, redirect, type Actions } from '@sveltejs/kit';
import { assertModuleAccess, kindFor, labelFor, listContent } from '$lib/server/admin';
import { audit, passwordHash } from '$lib/server/auth';
import { cleanText } from '$lib/content.js';
import { hasValidMediaSignature } from '$lib/server/media.js';
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async ({ params, platform, locals, url }) => {
  const user = locals.user!;
  assertModuleAccess(user, params.module);
  const env = platform?.env;
  if (!env) return { module: params.module, title: params.module, rows: [], settings: {} };
  const kind = kindFor(params.module);
  if (kind) return { module: params.module, kind, title: `Kelola ${labelFor(kind)}`, rows: await listContent(env, kind, url.searchParams.get('q') ?? ''), settings: {} };
  if (params.module === 'konten') { const rows = await env.DB.prepare('SELECT key, status, active, updated_at FROM page_content ORDER BY key').all<{ key: string; status: string; active: number; updated_at: string }>(); return { module: params.module, title: 'Konten website', rows: rows.results, settings: {} }; }
  if (params.module === 'pesan-masuk') { const rows = await env.DB.prepare('SELECT id, reference, name, phone, service, status, created_at FROM inquiries ORDER BY created_at DESC LIMIT 50').all(); return { module: params.module, title: 'Pesan masuk', rows: rows.results, settings: {} }; }
  if (params.module === 'media') { const rows = await env.DB.prepare('SELECT id, original_filename, content_type, size, alt, caption, created_at FROM media ORDER BY created_at DESC LIMIT 50').all(); return { module: params.module, title: 'Media library', rows: rows.results, settings: {} }; }
  if (params.module === 'pengaturan') { const rows = await env.DB.prepare('SELECT key, value FROM site_settings').all<{key:string;value:string}>(); return { module: params.module, title: 'Pengaturan global', rows: [], settings: Object.fromEntries(rows.results.map((row) => [row.key, row.value])) }; }
  if (params.module === 'pengguna') { const rows = await env.DB.prepare('SELECT id, name, email, role, status, last_login_at FROM users ORDER BY created_at DESC').all(); return { module: params.module, title: 'Pengguna admin', rows: rows.results, settings: {} }; }
  if (params.module === 'audit-log') { const rows = await env.DB.prepare('SELECT a.action, a.entity, a.summary, a.created_at, u.name FROM audit_logs a LEFT JOIN users u ON u.id = a.actor_id ORDER BY a.created_at DESC LIMIT 100').all(); return { module: params.module, title: 'Audit log', rows: rows.results, settings: {} }; }
  return { module: params.module, title: 'Modul tidak ditemukan', rows: [], settings: {} };
};

export const actions: Actions = {
  saveSettings: async ({ request, platform, locals }) => { const env = platform?.env; if (!env) return fail(503); assertModuleAccess(locals.user!, 'pengaturan'); const form = await request.formData(); for (const key of ['company_name', 'tagline', 'site_description', 'phone', 'email', 'address', 'instagram_url', 'linkedin_url', 'whatsapp_number', 'whatsapp_template', 'site_url', 'default_title', 'default_meta_description']) await env.DB.prepare('INSERT INTO site_settings (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP').bind(key, cleanText(form.get(key), 500)).run(); await audit(env, locals.user!.id, 'UPDATE', 'SETTINGS', null, 'Memperbarui pengaturan global'); return { saved: true }; },
  saveSection: async ({ request, platform, locals }) => { const env = platform?.env; if (!env) return fail(503); assertModuleAccess(locals.user!, 'konten'); const form = await request.formData(); const key = cleanText(form.get('key'), 80); if (!['hero','about','services_home','projects_home','why_hd','process','final_cta'].includes(key)) return fail(422, { error: 'Section tidak valid.' }); const data = JSON.stringify({ eyebrow: cleanText(form.get('eyebrow'), 80), heading: cleanText(form.get('heading'), 180), body: cleanText(form.get('body'), 3000), cta_label: cleanText(form.get('cta_label'), 80), cta_href: cleanText(form.get('cta_href'), 200) }); await env.DB.prepare('INSERT INTO page_content (key, data, status, active, updated_at) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET data=excluded.data, status=excluded.status, active=excluded.active, updated_at=CURRENT_TIMESTAMP').bind(key, data, cleanText(form.get('status'), 20) === 'PUBLISHED' ? 'PUBLISHED' : 'DRAFT', form.get('active') ? 1 : 0).run(); await audit(env, locals.user!.id, 'UPDATE', 'PAGE_CONTENT', key, `Memperbarui ${key}`); return { saved: true }; },
  createUser: async ({ request, platform, locals }) => { const env = platform?.env; const user = locals.user!; if (!env || user.role !== 'SUPER_ADMIN') return fail(403); const form = await request.formData(); const email = cleanText(form.get('email'), 254).toLowerCase(); const password = String(form.get('password') ?? ''); const role = cleanText(form.get('role'), 20); if (!email || password.length < 12 || !['EDITOR', 'SUPER_ADMIN'].includes(role)) return fail(422, { error: 'Gunakan email valid, password minimal 12 karakter, dan role yang tersedia.' }); try { const credentials = await passwordHash(password); const id = crypto.randomUUID(); await env.DB.prepare('INSERT INTO users (id, name, email, password_hash, password_salt, password_iterations, role) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(id, cleanText(form.get('name'), 100), email, credentials.hash, credentials.salt, credentials.iterations, role).run(); await audit(env, user.id, 'CREATE', 'USER', id, `Membuat user ${email}`); return { saved: true }; } catch { return fail(409, { error: 'Email pengguna sudah digunakan.' }); } },
  upload: async ({ request, platform, locals }) => { const env = platform?.env; if (!env) return fail(503); assertModuleAccess(locals.user!, 'media'); const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File) || !file.size) return fail(422, { error: 'Pilih file untuk diupload.' }); const allowed = new Map([['image/jpeg', 10 * 1024 * 1024], ['image/png', 10 * 1024 * 1024], ['image/webp', 10 * 1024 * 1024], ['image/avif', 10 * 1024 * 1024], ['application/pdf', 20 * 1024 * 1024]]); if (!allowed.has(file.type) || file.size > allowed.get(file.type)!) return fail(422, { error: 'Format atau ukuran file tidak sesuai.' }); const bytes = new Uint8Array(await file.arrayBuffer()); if (!hasValidMediaSignature(bytes, file.type)) return fail(422, { error: 'Isi file tidak sesuai dengan format yang dipilih.' }); const id = crypto.randomUUID(); const ext = ({ 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp', 'image/avif': 'avif', 'application/pdf': 'pdf' } as Record<string, string>)[file.type]; await env.MEDIA.put(`media/${id}.${ext}`, bytes, { httpMetadata: { contentType: file.type } }); await env.DB.prepare('INSERT INTO media (id, object_key, original_filename, content_type, size, alt, caption, uploader_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(id, `media/${id}.${ext}`, cleanText(file.name, 255), file.type, file.size, cleanText(form.get('alt'), 250), cleanText(form.get('caption'), 500), locals.user!.id).run(); await audit(env, locals.user!.id, 'UPLOAD', 'MEDIA', id, `Mengunggah ${file.name}`); return { uploaded: true }; },
  updateMedia: async ({ request, platform, locals }) => { const env = platform?.env; if (!env) return fail(503); assertModuleAccess(locals.user!, 'media'); const form = await request.formData(); const id = cleanText(form.get('id'), 80); if (!id) return fail(422, { error: 'Media tidak valid.' }); await env.DB.prepare('UPDATE media SET alt = ?, caption = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').bind(cleanText(form.get('alt'), 250), cleanText(form.get('caption'), 500), id).run(); await audit(env, locals.user!.id, 'UPDATE', 'MEDIA', id, 'Memperbarui metadata media'); return { saved: true }; },
  deleteMedia: async ({ request, platform, locals }) => { const env = platform?.env; if (!env) return fail(503); assertModuleAccess(locals.user!, 'media'); const id = cleanText((await request.formData()).get('id'), 80); const media = await env.DB.prepare('SELECT object_key FROM media WHERE id = ?').bind(id).first<{ object_key: string }>(); if (!media) return fail(404, { error: 'Media tidak ditemukan.' }); const references = await env.DB.prepare("SELECT COUNT(*) AS total FROM content_items WHERE json_extract(data, '$.cover_media_id') = ? OR json_extract(data, '$.media_id') = ? OR json_extract(data, '$.photo_media_id') = ? OR json_extract(data, '$.logo_media_id') = ? OR json_extract(data, '$.image_media_id') = ? OR json_extract(data, '$.pdf_media_id') = ?").bind(id, id, id, id, id, id).first<{ total: number }>(); if (Number(references?.total ?? 0)) return fail(409, { error: 'Media masih dipakai konten. Lepaskan pilihan media dari konten tersebut terlebih dahulu.' }); await env.MEDIA.delete(media.object_key); await env.DB.prepare('DELETE FROM media WHERE id = ?').bind(id).run(); await audit(env, locals.user!.id, 'DELETE', 'MEDIA', id, 'Menghapus media'); return { saved: true }; }
};
