import { canChangeAdmin, canManage, isAdminRoute } from './permissions.js';

type Role = 'SUPER_ADMIN' | 'EDITOR';
type ContentKind = 'LAYANAN' | 'PROYEK' | 'ARTIKEL' | 'GALERI' | 'TESTIMONI' | 'KLIEN' | 'SERTIFIKASI';
type RuntimeEnv = Env & { BOOTSTRAP_ADMIN_EMAIL?: string; BOOTSTRAP_ADMIN_PASSWORD?: string };
type User = { id: string; name: string; email: string; role: Role; status: string };

const contentRoutes: Record<string, ContentKind> = {
  layanan: 'LAYANAN', proyek: 'PROYEK', artikel: 'ARTIKEL', galeri: 'GALERI',
  testimoni: 'TESTIMONI', klien: 'KLIEN', sertifikasi: 'SERTIFIKASI',
};
const labels: Record<ContentKind, string> = {
  LAYANAN: 'Layanan', PROYEK: 'Proyek', ARTIKEL: 'Artikel', GALERI: 'Galeri',
  TESTIMONI: 'Testimoni', KLIEN: 'Klien & Partner', SERTIFIKASI: 'Sertifikasi',
};
const extraFields: Record<ContentKind, Array<{ key: string; label: string; multiline?: boolean }>> = {
  LAYANAN: [{key:'cover_media_id',label:'ID cover media'}, {key:'icon',label:'Icon optional'}, {key:'suitable_for',label:'Cocok untuk',multiline:true}, {key:'problems',label:'Masalah yang ditangani',multiline:true}, {key:'scope',label:'Scope pekerjaan',multiline:true}, {key:'deliverables',label:'Deliverables',multiline:true}, {key:'process',label:'Proses',multiline:true}, {key:'industry',label:'Jenis properti / industri'}, {key:'related_projects',label:'ID proyek terkait (pisahkan koma)'}],
  PROYEK: [{key:'cover_media_id',label:'ID cover media'}, {key:'client',label:'Klien'}, {key:'location',label:'Lokasi'}, {key:'sector',label:'Sektor'}, {key:'start_year',label:'Tahun mulai'}, {key:'end_year',label:'Tahun selesai'}, {key:'project_status',label:'Status proyek'}, {key:'challenge',label:'Tantangan',multiline:true}, {key:'solution',label:'Solusi',multiline:true}, {key:'scope',label:'Scope',multiline:true}, {key:'result',label:'Hasil',multiline:true}, {key:'service_ids',label:'ID layanan (pisahkan koma)'}, {key:'gallery_media_ids',label:'ID media galeri (pisahkan koma)'}],
  ARTIKEL: [{key:'author',label:'Penulis'}, {key:'cover_media_id',label:'ID cover media'}],
  GALERI: [{key:'media_id',label:'ID media'}, {key:'project_id',label:'ID proyek'}, {key:'alt',label:'Alt text'}, {key:'caption',label:'Caption',multiline:true}, {key:'visibility',label:'Visibility'}, {key:'sort_order',label:'Urutan'}],
  TESTIMONI: [{key:'position',label:'Posisi'}, {key:'company',label:'Perusahaan'}, {key:'quote',label:'Kutipan',multiline:true}, {key:'photo_media_id',label:'ID foto / logo media'}, {key:'project_id',label:'ID proyek terkait'}, {key:'active',label:'Aktif'}, {key:'sort_order',label:'Urutan'}],
  KLIEN: [{key:'partner_type',label:'Tipe (CLIENT / PARTNER)'}, {key:'logo_media_id',label:'ID logo media'}, {key:'logo_alt',label:'Alt logo'}, {key:'website',label:'Website'}, {key:'active',label:'Aktif'}, {key:'sort_order',label:'Urutan'}],
  SERTIFIKASI: [{key:'issuer',label:'Penerbit'}, {key:'certificate_number',label:'Nomor sertifikat'}, {key:'issue_year',label:'Tahun terbit'}, {key:'expiration_date',label:'Tanggal kedaluwarsa'}, {key:'image_media_id',label:'ID gambar media'}, {key:'pdf_media_id',label:'ID PDF media'}, {key:'active',label:'Aktif'}, {key:'sort_order',label:'Urutan'}],
};
const encoder = new TextEncoder();
const PBKDF2_ITERATIONS = 100000;

export default {
  async fetch(request: Request, env: RuntimeEnv, ctx: ExecutionContext): Promise<Response> {
    try {
      const url = new URL(request.url);
      const redirect = await env.DB.prepare('SELECT to_path, status_code FROM redirects WHERE from_path = ?').bind(url.pathname).first<{ to_path: string; status_code: number }>();
      if (redirect) return Response.redirect(new URL(redirect.to_path, url).toString(), redirect.status_code as 301 | 302 | 303 | 307 | 308);
      if (url.pathname === '/robots.txt') return text(robots(url), { 'Content-Type': 'text/plain; charset=utf-8' });
      if (url.pathname === '/sitemap.xml') return sitemap(url, env);
      if (url.pathname.startsWith('/media/')) return media(request, env, url.pathname.slice(7));
      if (url.pathname.startsWith('/api/')) return api(request, env, url, ctx);
      if (url.pathname.startsWith('/admin')) return admin(request, env, url, ctx);
      if (url.pathname === '/' || url.pathname === '/index.html') return homepage(request, env);
      if (isAsset(url.pathname)) return env.ASSETS.fetch(request);
      return publicPage(request, env, url);
    } catch (error) {
      console.error(JSON.stringify({ event: 'request_error', message: error instanceof Error ? error.message : 'unknown' }));
      return html(errorPage('Terjadi gangguan', 'Silakan coba lagi dalam beberapa saat.'), 500);
    }
  },
};

function isAsset(path: string) { return path.startsWith('/assets/') || /\.(css|js|png|jpg|jpeg|webp|avif|svg|ico)$/i.test(path); }
function escape(value: unknown) { return String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]!)); }
function text(body: string, headers: HeadersInit = {}) { return new Response(body, { headers: { 'X-Content-Type-Options': 'nosniff', ...headers } }); }
function html(body: string, status = 200, headers: HeadersInit = {}) { return new Response(body, { status, headers: securityHeaders(headers) }); }
function redirect(location: string | URL, headers: HeadersInit = {}) { return new Response(null, { status: 302, headers: { Location: String(location), ...headers } }); }
function securityHeaders(headers: HeadersInit) {
  return { 'Content-Type': 'text/html; charset=utf-8', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=()', 'Content-Security-Policy': "default-src 'self'; img-src 'self' data: https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'", ...headers };
}
function document(title: string, content: string, options: { description?: string; canonical?: string; noindex?: boolean; user?: User } = {}) {
  const canonical = options.canonical ? `<link rel="canonical" href="${escape(options.canonical)}">` : '';
  const robots = options.noindex ? '<meta name="robots" content="noindex,nofollow">' : '';
  const description = options.description ?? 'HD Karya Bandung'; const social = options.noindex ? '' : `<meta property="og:type" content="website"><meta property="og:site_name" content="HD Karya Bandung"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}">${options.canonical ? `<meta property="og:url" content="${escape(options.canonical)}">` : ''}`;
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}">${canonical}${robots}${social}<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Calistoga&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"></head><body class="${options.user ? 'admin-body' : 'public-body'}">${options.user ? adminShell(content, options.user) : content}<script src="/script.js"></script></body></html>`;
}
async function homepage(request: Request, env: RuntimeEnv) { const asset = await env.ASSETS.fetch(request); const url = new URL(request.url); const rows = await env.DB.prepare("SELECT key, data FROM page_content WHERE status = 'PUBLISHED' AND active = 1").all<{key:string;data:string}>(); const values = new Map(rows.results.map(row => [row.key, safeJson(row.data)])); const transform = new HTMLRewriter().on('head', { element(element) { element.append(`<link rel="canonical" href="${escape(url.origin + '/')}"><meta property="og:type" content="website"><meta property="og:site_name" content="HD Karya Bandung"><meta property="og:url" content="${escape(url.origin + '/')}"><script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'GeneralContractor', name: 'HD Karya Bandung', url: url.origin + '/', areaServed: 'Bandung' })}</script>`, { html: true }); } }); for (const [key, data] of values) { for (const field of ['eyebrow','heading','body'] as const) { const value = data[field]; if (value) transform.on(`[data-cms=\"${key}-${field}\"]`, { element(element) { element.setInnerContent(value); } }); } if (key === 'hero' && data.cta_label) transform.on('[data-cms="hero-cta"]', { element(element) { element.setInnerContent(data.cta_label); if (data.cta_href?.startsWith('/')) element.setAttribute('href', data.cta_href); } }); } const rewritten = transform.transform(asset); const headers = new Headers(securityHeaders(rewritten.headers)); headers.delete('content-length'); return new Response(rewritten.body, { status: rewritten.status, headers }); }
function errorPage(title: string, message: string) { return document(title, `<main class="simple-page"><p class="eyebrow"><span></span> HD Karya Bandung</p><h1>${escape(title)}</h1><p>${escape(message)}</p><a class="button button-accent" href="/">Kembali ke beranda</a></main>`, { noindex: true }); }

async function publicPage(request: Request, env: RuntimeEnv, url: URL): Promise<Response> {
  const path = url.pathname.replace(/^\/+|\/+$/g, '');
  if (path === 'tentang-kami') return html(publicLayout('Tentang HD Karya Bandung', 'Mengenal pendekatan kami dalam merancang dan membangun ruang.', `<h1>Tentang HD Karya Bandung</h1><p>Kami membangun dengan proses yang terbuka, material yang jujur, dan perhatian pada ruang yang benar-benar dipakai.</p><p class="lead">Dari percakapan awal hingga serah-terima, kami menjaga keputusan tetap jelas agar ruang yang dibangun benar-benar relevan untuk keseharian Anda.</p><a class="button button-accent" href="/kontak">Mulai konsultasi <span aria-hidden="true">↗</span></a>`, new URL(url.pathname, url).toString()), 200);
  if (path === 'kontak') return html(publicLayout('Kontak HD Karya Bandung', 'Mulai konsultasi konstruksi dan renovasi di Bandung.', contactForm(), new URL(url.pathname, url).toString()), 200);
  for (const [route, kind] of Object.entries(contentRoutes)) {
    if (path === route) return html(await listingPage(env, url, kind), 200);
    if (path.startsWith(`${route}/`)) return detailPage(env, url, kind, path.slice(route.length + 1));
  }
  return html(errorPage('Halaman tidak ditemukan', 'Kami tidak dapat menemukan halaman yang Anda cari.'), 404, { 'X-Robots-Tag': 'noindex' });
}
function publicHeader() {
  return `<a class="skip-link" href="#content">Lewati ke konten utama</a><header class="site-header"><a class="brand" href="/" aria-label="HD Karya Bandung, beranda"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>HD<br><strong>KARYA</strong></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span class="sr-only">Buka menu</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" /></svg></button><nav id="site-nav" aria-label="Navigasi utama"><a href="/tentang-kami">Tentang</a><a href="/layanan">Layanan</a><a href="/proyek">Proyek</a><a href="/artikel">Artikel</a><a href="/kontak" class="nav-cta">Mulai diskusi <span aria-hidden="true">↗</span></a></nav></header>`;
}
function publicLayout(title: string, description: string, main: string, canonical?: string) {
  return document(`${title} | HD Karya Bandung`, `${publicHeader()}<main id="content" class="simple-page"><p class="eyebrow"><span></span> Bandung & sekitarnya</p>${main}</main><footer class="site-footer"><a class="brand" href="/" aria-label="HD Karya Bandung, beranda"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>HD<br><strong>KARYA</strong></span></a><p>© HD Karya Bandung. Dibuat untuk ruang yang bertumbuh.</p><a href="#content">Kembali ke konten <span aria-hidden="true">↑</span></a></footer>`, { description, canonical });
}
async function listingPage(env: RuntimeEnv, url: URL, kind: ContentKind) {
  const rows = await env.DB.prepare("SELECT title, slug, summary, category FROM content_items WHERE kind = ? AND status = 'PUBLISHED' ORDER BY featured DESC, published_at DESC LIMIT 24").bind(kind).all<{ title: string; slug: string; summary: string; category: string }>();
  const cards = rows.results.length ? rows.results.map(row => `<article class="service-card"><span class="service-index">${escape(row.category || labels[kind])}</span><h2>${escape(row.title)}</h2><p>${escape(row.summary)}</p><a class="text-link" href="/${routeFor(kind)}/${escape(row.slug)}">Lihat detail <span aria-hidden="true">↗</span></a></article>`).join('') : `<article class="service-card"><span class="service-index">SEGERA HADIR</span><h2>${labels[kind]} sedang disiapkan</h2><p>Tim kami sedang merapikan informasi terbaru. Untuk kebutuhan proyek Anda, silakan mulai dari konsultasi singkat.</p><a class="text-link" href="/kontak">Hubungi kami <span aria-hidden="true">↗</span></a></article>`;
  return publicLayout(labels[kind], `${labels[kind]} HD Karya Bandung di Bandung.`, `<h1>${labels[kind]} HD Karya Bandung</h1><p>Informasi terbaru mengenai ${labels[kind].toLowerCase()} kami.</p><section class="service-grid public-grid">${cards}</section>`, new URL(url.pathname, url).toString());
}
async function detailPage(env: RuntimeEnv, url: URL, kind: ContentKind, slug: string): Promise<Response> {
  const item = await env.DB.prepare("SELECT * FROM content_items WHERE kind = ? AND slug = ? AND status = 'PUBLISHED'").bind(kind, slug).first<Record<string, string>>();
  if (!item) return html(errorPage('Halaman tidak ditemukan', 'Konten ini belum tersedia atau telah dipindahkan.'), 404, { 'X-Robots-Tag': 'noindex' });
  const title = item.seo_title || `${item.title} | HD Karya Bandung`;
  const description = item.meta_description || item.summary;
  const canonical = item.canonical_url || new URL(url.pathname, url).toString();
  const crumbs = `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Beranda</a><span>/</span><a href="/${routeFor(kind)}">${labels[kind]}</a><span>/</span><span aria-current="page">${escape(item.title)}</span></nav>`;
  const schema = JSON.stringify({ '@context': 'https://schema.org', '@type': kind === 'LAYANAN' ? 'Service' : 'Article', name: item.title, description, url: canonical });
  return html(document(title, `${publicHeader()}<main id="content" class="simple-page">${crumbs}<h1>${escape(item.title)}</h1><p class="lead">${escape(item.summary)}</p><div class="rich-content">${escape(item.body).replace(/\n/g, '<br>')}</div><a class="button button-accent" href="/kontak">Konsultasikan kebutuhan Anda</a></main><footer class="site-footer"><a class="brand" href="/" aria-label="HD Karya Bandung, beranda">HD KARYA</a><p>© HD Karya Bandung</p><a href="/${routeFor(kind)}">Kembali ke ${labels[kind]}</a></footer><script type="application/ld+json">${schema}</script>`, { description, canonical, noindex: item.index_status !== 'INDEX_FOLLOW' }), 200);
}
function routeFor(kind: ContentKind) { return Object.entries(contentRoutes).find(([, value]) => value === kind)?.[0] ?? ''; }
function contactForm() { return `<h1>Konsultasikan proyek Anda</h1><form method="post" action="/api/inquiries" class="public-form"><label>Nama<input name="name" required autocomplete="name"></label><label>Nomor telepon<input name="phone" required type="tel" autocomplete="tel"></label><label>Layanan<select name="service"><option>Bangun baru</option><option>Renovasi</option><option>Interior build</option></select></label><label>Pesan<textarea name="message" required rows="5"></textarea></label><button class="button button-accent">Kirim inquiry</button></form>`; }

async function admin(request: Request, env: RuntimeEnv, url: URL, ctx: ExecutionContext): Promise<Response> {
  await bootstrapAdmin(env);
  if (url.pathname === '/admin/login') return login(request, env, url);
  const user = await currentUser(request, env);
  if (!user) return redirect(new URL('/admin/login', url));
  if (request.method === 'POST') return adminPost(request, env, url, user, ctx);
  return adminGet(env, url, user);
}
async function bootstrapAdmin(env: RuntimeEnv) {
  const count = await env.DB.prepare('SELECT COUNT(*) AS count FROM users').first<{ count: number }>();
  if (Number(count?.count) || !env.BOOTSTRAP_ADMIN_EMAIL || !env.BOOTSTRAP_ADMIN_PASSWORD) return;
  const { hash, salt } = await passwordHash(env.BOOTSTRAP_ADMIN_PASSWORD);
  await env.DB.prepare('INSERT INTO users (id, name, email, password_hash, password_salt, role) VALUES (?, ?, ?, ?, ?, ?)').bind(crypto.randomUUID(), 'Administrator', env.BOOTSTRAP_ADMIN_EMAIL.toLowerCase(), hash, salt, 'SUPER_ADMIN').run();
}
async function login(request: Request, env: RuntimeEnv, url: URL): Promise<Response> {
  if (request.method === 'GET') return html(document('Masuk Admin | HD Karya Bandung', `<main class="login-page"><a class="brand" href="/">HD KARYA</a><form method="post" class="login-card"><p class="eyebrow"><span></span> Area terlindungi</p><h1>Masuk ke admin</h1><label>Email<input type="email" name="email" required autocomplete="username"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button class="button button-accent">Masuk</button></form></main>`, { noindex: true }), 200);
  if (!sameOrigin(request, url)) return html(errorPage('Permintaan ditolak', 'Permintaan harus berasal dari website ini.'), 403);
  const data = await request.formData(); const email = clean(data.get('email'), 254).toLowerCase(); const password = String(data.get('password') ?? '');
  const fingerprint = await sha256(`${request.headers.get('CF-Connecting-IP') ?? 'unknown'}:${email}`);
  const attempts = await env.DB.prepare("SELECT COUNT(*) AS count FROM login_attempts WHERE fingerprint = ? AND attempted_at > datetime('now', '-15 minutes')").bind(fingerprint).first<{ count: number }>();
  if (Number(attempts?.count) >= 10) return html(errorPage('Terlalu banyak percobaan', 'Coba lagi dalam 15 menit.'), 429);
  const user = await env.DB.prepare('SELECT * FROM users WHERE email = ? AND status = ?').bind(email, 'ACTIVE').first<User & { password_hash: string; password_salt: string }>();
  if (!user || !(await verifyPassword(password, user.password_hash, user.password_salt))) { await env.DB.prepare('INSERT INTO login_attempts (id, fingerprint) VALUES (?, ?)').bind(crypto.randomUUID(), fingerprint).run(); return html(document('Masuk Admin | HD Karya Bandung', `<main class="login-page"><form method="post" class="login-card"><h1>Masuk ke admin</h1><p role="alert">Email atau password tidak tepat.</p><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button class="button button-accent">Coba lagi</button></form></main>`, { noindex: true }), 401); }
  const token = crypto.randomUUID() + crypto.randomUUID();
  await env.DB.prepare('INSERT INTO sessions (id, user_id, token_hash, expires_at) VALUES (?, ?, ?, datetime(\'now\', \'+8 hours\'))').bind(crypto.randomUUID(), user.id, await sha256(token)).run();
  await env.DB.prepare('UPDATE users SET last_login_at = CURRENT_TIMESTAMP WHERE id = ?').bind(user.id).run();
  await audit(env, user.id, 'LOGIN', 'USER', user.id, 'Login berhasil');
  return redirect(new URL('/admin', url), { 'Set-Cookie': sessionCookie(token, url) });
}
async function currentUser(request: Request, env: RuntimeEnv): Promise<User | null> {
  const token = cookie(request.headers.get('Cookie') ?? '', 'hd_session'); if (!token) return null;
  return env.DB.prepare("SELECT u.id, u.name, u.email, u.role, u.status FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.token_hash = ? AND s.expires_at > CURRENT_TIMESTAMP AND u.status = 'ACTIVE'").bind(await sha256(token)).first<User>();
}
function cookie(header: string, name: string) { return header.split(';').map(part => part.trim().split('=')).find(([key]) => key === name)?.slice(1).join('='); }
function sessionCookie(token: string, url: URL) { return `hd_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=28800${url.protocol === 'https:' ? '; Secure' : ''}`; }
async function sha256(value: string) { const bytes = await crypto.subtle.digest('SHA-256', encoder.encode(value)); return btoa(String.fromCharCode(...new Uint8Array(bytes))); }
function bytesToBase64(bytes: Uint8Array) { return btoa(String.fromCharCode(...bytes)); }
function base64ToBytes(value: string) { return Uint8Array.from(atob(value), char => char.charCodeAt(0)); }
async function passwordHash(password: string, salt = crypto.getRandomValues(new Uint8Array(16))) { const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-256', salt, iterations: PBKDF2_ITERATIONS }, key, 256); return { hash: bytesToBase64(new Uint8Array(bits)), salt: bytesToBase64(salt) }; }
async function verifyPassword(password: string, hash: string, salt: string) { const candidate = await passwordHash(password, base64ToBytes(salt)); return constantTimeEqual(encoder.encode(candidate.hash), encoder.encode(hash)); }
function constantTimeEqual(a: Uint8Array, b: Uint8Array) { let difference = a.length ^ b.length; const length = Math.max(a.length, b.length); for (let index = 0; index < length; index += 1) difference |= (a[index] ?? 0) ^ (b[index] ?? 0); return difference === 0; }
function clean(value: FormDataEntryValue | null, max = 3000) { return String(value ?? '').trim().slice(0, max); }
async function audit(env: RuntimeEnv, actorId: string | null, action: string, entity: string, entityId: string | null, summary: string) { await env.DB.prepare('INSERT INTO audit_logs (id, actor_id, action, entity, entity_id, summary) VALUES (?, ?, ?, ?, ?, ?)').bind(crypto.randomUUID(), actorId, action, entity, entityId, summary.slice(0, 500)).run(); }

async function adminGet(env: RuntimeEnv, url: URL, user: User): Promise<Response> {
  const parts = url.pathname.split('/').filter(Boolean); const module = parts[1] ?? '';
  if (!module) return html(document('Dashboard | HD Karya Bandung', await dashboard(env), { noindex: true, user }));
  if (!canManage(user.role, module)) return html(errorPage('Akses ditolak', 'Role Anda tidak memiliki izin untuk modul ini.'), 403);
  if (module === 'konten') return html(document('Konten Website | HD Karya Bandung', await contentEditor(env, url), { noindex: true, user }));
  if (module === 'media') return html(document('Media Library | HD Karya Bandung', await mediaAdmin(env), { noindex: true, user }));
  if (module === 'pesan-masuk') return html(document('Pesan Masuk | HD Karya Bandung', await inquiryAdmin(env, parts[2]), { noindex: true, user }));
  if (module === 'pengaturan') return html(document('Pengaturan | HD Karya Bandung', await settingsAdmin(env), { noindex: true, user }));
  if (module === 'pengguna') return html(document('Pengguna | HD Karya Bandung', await usersAdmin(env, user), { noindex: true, user }));
  if (module === 'audit-log') return html(document('Audit Log | HD Karya Bandung', await auditAdmin(env), { noindex: true, user }));
  const kind = contentRoutes[module]; if (kind) return html(document(`${labels[kind]} | HD Karya Bandung`, await contentAdmin(env, url, kind, parts[2]), { noindex: true, user }));
  return html(errorPage('Modul tidak ditemukan', 'Pilih modul dari navigasi admin.'), 404);
}
function adminShell(content: string, user: User) { const nav = [['', 'Dashboard'], ['konten','Konten'], ['layanan','Layanan'], ['proyek','Proyek'], ['galeri','Galeri'], ['artikel','Artikel'], ['media','Media'], ['pesan-masuk','Inquiry'], ['testimoni','Testimoni'], ['klien','Klien'], ['sertifikasi','Sertifikasi'], ['pengaturan','Pengaturan'], ['pengguna','Pengguna'], ['audit-log','Audit log']].filter(([path]) => !path || canManage(user.role, path)).map(([path,label]) => `<a href="/admin${path ? `/${path}` : ''}">${label}</a>`).join(''); return `<div class="admin-layout"><aside class="admin-sidebar"><a class="brand" href="/admin">HD KARYA</a><nav>${nav}</nav><form method="post" action="/admin/logout"><button>Keluar</button></form></aside><main class="admin-main"><header class="admin-topbar"><span>${escape(user.name)} · ${escape(user.role)}</span><a href="/" target="_blank" rel="noreferrer">Lihat website ↗</a></header>${content}</main></div>`; }
async function dashboard(env: RuntimeEnv) { const counts = await env.DB.prepare("SELECT kind, status, COUNT(*) AS total FROM content_items GROUP BY kind, status").all<{kind: string;status:string;total:number}>(); const inquiry = await env.DB.prepare("SELECT COUNT(*) AS total FROM inquiries WHERE status = 'NEW'").first<{total:number}>(); const cards = [['Proyek', count(counts.results,'PROYEK')],['Layanan',count(counts.results,'LAYANAN')],['Artikel',count(counts.results,'ARTIKEL')],['Inquiry baru',Number(inquiry?.total ?? 0)]].map(([label,value]) => `<article class="metric"><span>${label}</span><strong>${value}</strong></article>`).join(''); return `<section class="admin-page"><p class="eyebrow"><span></span> Dashboard</p><h1>Ringkasan konten</h1><div class="metrics">${cards}</div><div class="quick-actions"><a class="button button-accent" href="/admin/proyek/baru">Tambah Proyek</a><a class="button" href="/admin/media">Upload Media</a><a class="button" href="/admin/artikel/baru">Tambah Artikel</a></div></section>`; }
function count(rows: {kind:string;total:number}[], kind: string) { return rows.filter(row => row.kind === kind).reduce((total,row) => total + Number(row.total), 0); }
async function contentEditor(env: RuntimeEnv, url: URL) { const keys = ['hero','about','services_home','projects_home','why_hd','process','final_cta']; const rows = await env.DB.prepare('SELECT key, status, active, updated_at FROM page_content ORDER BY key').all<{key:string;status:string;active:number;updated_at:string}>(); const map = new Map(rows.results.map(row => [row.key,row])); const section = keys.includes(url.searchParams.get('section') ?? '') ? url.searchParams.get('section')! : ''; return `<section class="admin-page"><p class="eyebrow"><span></span> Konten website</p><h1>Section homepage</h1><p>Edit section yang sudah ditentukan. Perubahan hanya tampil saat statusnya dipublikasikan dan aktif.</p><div class="admin-list">${keys.map(key => { const row = map.get(key); return `<a class="admin-row" href="/admin/konten?section=${key}"><strong>${escape(key.replace('_',' '))}</strong><span>${row ? `${row.status} · ${row.active ? 'aktif' : 'nonaktif'}` : 'Belum diatur'}</span><span>→</span></a>`; }).join('')}</div>${section ? await contentSectionForm(env, section) : ''}</section>`; }
async function contentSectionForm(env: RuntimeEnv, key: string) { const item = await env.DB.prepare('SELECT * FROM page_content WHERE key = ?').bind(key).first<Record<string, unknown>>() ?? {}; const data = safeJson(item.data); const value = (name: string) => escape(data[name] ?? ''); const label = key.replaceAll('_', ' '); const needsHeading = ['hero','services_home','projects_home','process','final_cta'].includes(key); return `<form method="post" action="/admin/konten" class="admin-form" data-unsaved-warning><input type="hidden" name="key" value="${escape(key)}"><fieldset><legend>${escape(label)}</legend><label>Label kecil<input name="eyebrow" value="${value('eyebrow')}"></label>${needsHeading ? `<label>Judul<input name="heading" value="${value('heading')}" required maxlength="180"></label>` : '<input type="hidden" name="heading" value="">'}<label>Deskripsi<textarea name="body" rows="6" required maxlength="3000">${value('body')}</textarea></label>${key === 'hero' || key === 'final_cta' ? `<div class="form-row"><label>Teks CTA<input name="cta_label" value="${value('cta_label')}" maxlength="80"></label><label>Tujuan CTA<input name="cta_href" value="${value('cta_href')}" pattern="/(?:[a-z0-9-]+)?" placeholder="/kontak"></label></div>` : ''}</fieldset><fieldset><legend>Publikasi</legend><div class="form-row"><label>Status<select name="status">${['DRAFT','PUBLISHED'].map(option => `<option ${item.status === option ? 'selected' : ''}>${option}</option>`).join('')}</select></label><label class="checkbox"><input type="checkbox" name="active" ${Number(item.active) ? 'checked' : ''}> Tampilkan section</label></div></fieldset><div class="sticky-actions"><button class="button button-accent">Simpan section</button></div></form>`; }
function safeJson(value: unknown): Record<string, string> { try { const result = JSON.parse(String(value ?? '{}')); return typeof result === 'object' && result ? result as Record<string, string> : {}; } catch { return {}; } }

async function contentAdmin(env: RuntimeEnv, url: URL, kind: ContentKind, id?: string) {
  if (id === 'baru') return contentForm(kind);
  if (id) {
    const item = await env.DB.prepare('SELECT * FROM content_items WHERE id = ? AND kind = ?').bind(id, kind).first<Record<string, unknown>>();
    return item ? contentForm(kind, item) : '<section class="admin-page"><h1>Konten tidak ditemukan</h1></section>';
  }
  const q = clean(url.searchParams.get('q'), 100); const status = clean(url.searchParams.get('status'), 20);
  const predicates = ['kind = ?']; const values: string[] = [kind];
  if (status) { predicates.push('status = ?'); values.push(status); }
  if (q) { predicates.push("(title LIKE ? OR slug LIKE ? OR summary LIKE ?)"); values.push(`%${q}%`, `%${q}%`, `%${q}%`); }
  const page = Math.max(1, Number(url.searchParams.get('page') ?? 1)); values.push('25', String((page - 1) * 25));
  const rows = await env.DB.prepare(`SELECT id, title, slug, category, status, featured, updated_at FROM content_items WHERE ${predicates.join(' AND ')} ORDER BY updated_at DESC LIMIT ? OFFSET ?`).bind(...values).all<{id:string;title:string;slug:string;category:string;status:string;featured:number;updated_at:string}>();
  return `<section class="admin-page"><div class="page-title"><div><p class="eyebrow"><span></span> ${labels[kind]}</p><h1>Kelola ${labels[kind]}</h1></div><a class="button button-accent" href="/admin/${routeFor(kind)}/baru">Tambah ${labels[kind].slice(0,-1) || labels[kind]}</a></div><form class="filters" method="get"><input name="q" value="${escape(q)}" placeholder="Cari judul, slug, atau deskripsi"><select name="status"><option value="">Semua status</option>${['DRAFT','PUBLISHED','ARCHIVED'].map(value => `<option ${status === value ? 'selected' : ''}>${value}</option>`).join('')}</select><button class="button">Filter</button><a href="/admin/${routeFor(kind)}">Reset</a></form><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Kategori</th><th>Status</th><th>Featured</th><th>Diperbarui</th><th></th></tr></thead><tbody>${rows.results.length ? rows.results.map(row => `<tr><td><strong>${escape(row.title)}</strong><small>/${escape(row.slug)}</small></td><td>${escape(row.category)}</td><td><span class="status ${row.status.toLowerCase()}">${row.status}</span></td><td>${row.featured ? 'Ya' : '—'}</td><td>${escape(row.updated_at)}</td><td><a href="/admin/${routeFor(kind)}/${row.id}">Edit</a></td></tr>`).join('') : '<tr><td colspan="6">Belum ada konten. Tambahkan item pertama.</td></tr>'}</tbody></table></div></section>`;
}
function contentForm(kind: ContentKind, item: Record<string, unknown> = {}) {
  const value = (key: string) => escape(item[key] ?? ''); const checked = item.featured ? 'checked' : '';
  return `<section class="admin-page"><div class="page-title"><div><p class="eyebrow"><span></span> ${labels[kind]}</p><h1>${item.id ? `Edit ${labels[kind]}` : `Tambah ${labels[kind]}`}</h1></div><a href="/admin/${routeFor(kind)}">Kembali</a></div><form method="post" class="admin-form" data-unsaved-warning><input type="hidden" name="id" value="${value('id')}"><fieldset><legend>Basic information</legend><label>Judul<input name="title" required value="${value('title')}"></label><div class="form-row"><label>Slug<input name="slug" required pattern="[a-z0-9-]+" value="${value('slug')}"></label><label>Kategori<input name="category" value="${value('category')}"></label></div><label>Deskripsi singkat<textarea name="summary" required rows="3">${value('summary')}</textarea></label></fieldset><fieldset><legend>Content</legend><label>Konten / detail<textarea name="body" rows="12">${value('body')}</textarea></label><p class="help">Gunakan teks biasa yang aman. Rich text membutuhkan sanitization server-side sebelum diaktifkan.</p></fieldset>${extraFieldsForm(kind,item)}<fieldset><legend>SEO</legend><label>SEO title<input name="seo_title" value="${value('seo_title')}"></label><label>Meta description<textarea name="meta_description" maxlength="160" rows="3">${value('meta_description')}</textarea></label><div class="form-row"><label>Canonical override<input name="canonical_url" type="url" value="${value('canonical_url')}"></label><label>Index status<select name="index_status">${['INDEX_FOLLOW','NOINDEX_FOLLOW','NOINDEX_NOFOLLOW'].map(option => `<option ${value('index_status') === option ? 'selected' : ''}>${option}</option>`).join('')}</select></label></div></fieldset><fieldset><legend>Publishing</legend><div class="form-row"><label>Status<select name="status">${['DRAFT','PUBLISHED','ARCHIVED'].map(option => `<option ${value('status') === option ? 'selected' : ''}>${option}</option>`).join('')}</select></label><label class="checkbox"><input type="checkbox" name="featured" ${checked}> Featured</label></div></fieldset><div class="sticky-actions"><button class="button button-accent">Simpan perubahan</button>${item.id ? `<button class="button danger" formaction="/admin/${routeFor(kind)}/${value('id')}/delete" formmethod="post" data-confirm="Arsipkan konten ini?">Arsipkan</button>` : ''}</div></form></section>`;
}
function extraFieldsForm(kind: ContentKind, item: Record<string, unknown>) { const data = safeJson(item.data); return `<fieldset><legend>Detail ${labels[kind]}</legend>${extraFields[kind].map(field => `<label>${escape(field.label)}${field.multiline ? `<textarea name="meta_${field.key}" rows="3">${escape(data[field.key] ?? '')}</textarea>` : `<input name="meta_${field.key}" value="${escape(data[field.key] ?? '')}">`}</label>`).join('')}</fieldset>`; }
async function mediaAdmin(env: RuntimeEnv) { const rows = await env.DB.prepare('SELECT id, original_filename, content_type, size, alt, caption, created_at FROM media ORDER BY created_at DESC LIMIT 50').all<{id:string;original_filename:string;content_type:string;size:number;alt:string;caption:string;created_at:string}>(); return `<section class="admin-page"><div class="page-title"><div><p class="eyebrow"><span></span> Media</p><h1>Media library</h1></div></div><form class="upload-form" method="post" action="/admin/media/upload" enctype="multipart/form-data"><label>Upload JPEG, PNG, WebP, AVIF, atau PDF<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif,application/pdf" required></label><label>Alt text<input name="alt" required maxlength="250"></label><label>Caption<input name="caption" maxlength="500"></label><button class="button button-accent">Upload media</button></form><div class="media-grid">${rows.results.length ? rows.results.map(row => `<article><a href="/media/${row.id}" target="_blank" rel="noreferrer">${escape(row.original_filename)}</a><small>${escape(row.content_type)} · ${Math.ceil(row.size / 1024)} KB</small><form method="post" action="/admin/media/${row.id}"><label>Alt text<input name="alt" required maxlength="250" value="${escape(row.alt)}"></label><label>Caption<input name="caption" maxlength="500" value="${escape(row.caption)}"></label><div class="quick-actions"><button class="button">Simpan</button><button class="button danger" formaction="/admin/media/${row.id}/delete" data-confirm="Hapus media ini secara permanen?">Hapus</button></div></form></article>`).join('') : '<p>Belum ada media.</p>'}</div></section>`; }
async function inquiryAdmin(env: RuntimeEnv, id?: string) { if (id) { const row = await env.DB.prepare('SELECT * FROM inquiries WHERE id = ?').bind(id).first<Record<string,unknown>>(); if (!row) return '<section class="admin-page"><h1>Inquiry tidak ditemukan</h1></section>'; return `<section class="admin-page"><p class="eyebrow"><span></span> ${escape(row.reference)}</p><h1>${escape(row.name)}</h1><dl class="detail-list"><dt>Telepon</dt><dd>${escape(row.phone)}</dd><dt>Email</dt><dd>${escape(row.email)}</dd><dt>Layanan</dt><dd>${escape(row.service)}</dd><dt>Pesan</dt><dd>${escape(row.message)}</dd></dl><form method="post" action="/admin/inquiries/${escape(row.id)}/status" class="admin-form"><label>Status<select name="status">${['NEW','CONTACTED','QUALIFIED','CLOSED','SPAM'].map(status => `<option ${row.status === status ? 'selected' : ''}>${status}</option>`).join('')}</select></label><label>Catatan internal<textarea name="internal_note" rows="5">${escape(row.internal_note)}</textarea></label><button class="button button-accent">Simpan proses inquiry</button></form></section>`; } const rows = await env.DB.prepare('SELECT id, reference, name, service, phone, status, created_at FROM inquiries ORDER BY created_at DESC LIMIT 50').all<{id:string;reference:string;name:string;service:string;phone:string;status:string;created_at:string}>(); return `<section class="admin-page"><p class="eyebrow"><span></span> Inquiry</p><h1>Pesan masuk</h1><div class="table-wrap"><table><thead><tr><th>Referensi</th><th>Nama</th><th>Layanan</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>${rows.results.length ? rows.results.map(row => `<tr><td><a href="/admin/pesan-masuk/${row.id}">${escape(row.reference)}</a></td><td>${escape(row.name)}<small>${escape(row.phone)}</small></td><td>${escape(row.service)}</td><td>${escape(row.status)}</td><td>${escape(row.created_at)}</td></tr>`).join('') : '<tr><td colspan="5">Belum ada inquiry.</td></tr>'}</tbody></table></div></section>`; }

async function settingsAdmin(env: RuntimeEnv) { const rows = await env.DB.prepare('SELECT key, value FROM site_settings').all<{key:string;value:string}>(); const values = Object.fromEntries(rows.results.map(row => [row.key, row.value])); const value = (key: string) => escape(values[key] ?? ''); return `<section class="admin-page"><p class="eyebrow"><span></span> Pengaturan</p><h1>Pengaturan global</h1><form method="post" action="/admin/settings" class="admin-form"><fieldset><legend>Company</legend><label>Nama perusahaan<input name="company_name" value="${value('company_name')}" required></label><label>Tagline<input name="tagline" value="${value('tagline')}"></label><label>Deskripsi singkat<textarea name="site_description" rows="3">${value('site_description')}</textarea></label></fieldset><fieldset><legend>Contact</legend><div class="form-row"><label>Telepon<input name="phone" type="tel" value="${value('phone')}"></label><label>Email<input name="email" type="email" value="${value('email')}"></label></div><label>Alamat<textarea name="address" rows="3">${value('address')}</textarea></label></fieldset><fieldset><legend>Social</legend><label>Instagram<input name="instagram_url" type="url" value="${value('instagram_url')}"></label><label>Facebook<input name="facebook_url" type="url" value="${value('facebook_url')}"></label><label>LinkedIn<input name="linkedin_url" type="url" value="${value('linkedin_url')}"></label></fieldset><fieldset><legend>WhatsApp</legend><label>Nomor WhatsApp<input name="whatsapp_number" value="${value('whatsapp_number')}"></label><label>Template pesan<textarea name="whatsapp_template" rows="3">${value('whatsapp_template')}</textarea></label></fieldset><fieldset><legend>SEO global</legend><label>Site URL<input name="site_url" type="url" value="${value('site_url')}"></label><label>Default title<input name="default_title" value="${value('default_title')}"></label><label>Default meta description<textarea name="default_meta_description" maxlength="160" rows="3">${value('default_meta_description')}</textarea></label></fieldset><fieldset><legend>Analytics</legend><label>GA4 measurement ID<input name="ga4_measurement_id" value="${value('ga4_measurement_id')}"></label><label>Google Tag Manager ID<input name="gtm_id" value="${value('gtm_id')}"></label></fieldset><button class="button button-accent">Simpan pengaturan</button></form></section>`; }
async function usersAdmin(env: RuntimeEnv, actor: User) { const rows = await env.DB.prepare('SELECT id, name, email, role, status, last_login_at, created_at FROM users ORDER BY created_at DESC').all<{id:string;name:string;email:string;role:Role;status:string;last_login_at:string;created_at:string}>(); return `<section class="admin-page"><p class="eyebrow"><span></span> SUPER_ADMIN</p><h1>Pengguna admin</h1><form method="post" action="/admin/pengguna" class="admin-form compact"><div class="form-row"><label>Nama<input name="name" required></label><label>Email<input name="email" type="email" required></label></div><div class="form-row"><label>Password sementara<input name="password" type="password" minlength="12" required></label><label>Role<select name="role"><option>EDITOR</option><option>SUPER_ADMIN</option></select></label></div><button class="button button-accent">Buat pengguna</button></form><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Role & status</th><th>Password baru</th><th>Login terakhir</th><th></th></tr></thead><tbody>${rows.results.map(row => { const formId = `user-${row.id}`; return `<tr><td><strong>${escape(row.name)}</strong><small>${escape(row.email)}</small><form id="${formId}" method="post" action="/admin/pengguna/${row.id}"></form></td><td><select form="${formId}" name="role">${(['EDITOR','SUPER_ADMIN'] as Role[]).map(role => `<option ${row.role === role ? 'selected' : ''}>${role}</option>`).join('')}</select><select form="${formId}" name="status">${['ACTIVE','DISABLED'].map(status => `<option ${row.status === status ? 'selected' : ''}>${status}</option>`).join('')}</select></td><td><input form="${formId}" type="password" name="password" minlength="12" autocomplete="new-password" placeholder="Kosongkan bila tetap"></td><td>${escape(row.last_login_at || 'Belum pernah')}</td><td><button form="${formId}" class="button" ${actor.id === row.id ? 'title="Akun sendiri tidak dapat diturunkan atau dinonaktifkan"' : ''}>Simpan</button></td></tr>`; }).join('')}</tbody></table></div></section>`; }
async function auditAdmin(env: RuntimeEnv) { const rows = await env.DB.prepare('SELECT a.action, a.entity, a.summary, a.created_at, u.name FROM audit_logs a LEFT JOIN users u ON u.id = a.actor_id ORDER BY a.created_at DESC LIMIT 100').all<{action:string;entity:string;summary:string;created_at:string;name:string}>(); return `<section class="admin-page"><p class="eyebrow"><span></span> SUPER_ADMIN</p><h1>Audit log</h1><div class="table-wrap"><table><thead><tr><th>Aktor</th><th>Aksi</th><th>Entitas</th><th>Ringkasan</th><th>Tanggal</th></tr></thead><tbody>${rows.results.length ? rows.results.map(row => `<tr><td>${escape(row.name || 'Sistem')}</td><td>${escape(row.action)}</td><td>${escape(row.entity)}</td><td>${escape(row.summary)}</td><td>${escape(row.created_at)}</td></tr>`).join('') : '<tr><td colspan="5">Belum ada aktivitas.</td></tr>'}</tbody></table></div></section>`; }

async function adminPost(request: Request, env: RuntimeEnv, url: URL, user: User, ctx: ExecutionContext): Promise<Response> {
  const parts = url.pathname.split('/').filter(Boolean); const module = parts[1] ?? '';
  if (!sameOrigin(request, url)) return html(errorPage('Permintaan ditolak', 'Permintaan harus berasal dari website ini.'), 403);
  if (module === 'logout') { const token = cookie(request.headers.get('Cookie') ?? '', 'hd_session'); if (token) await env.DB.prepare('DELETE FROM sessions WHERE token_hash = ?').bind(await sha256(token)).run(); await audit(env, user.id, 'LOGOUT', 'USER', user.id, 'Logout'); return redirect(new URL('/admin/login', url), { 'Set-Cookie': 'hd_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0' }); }
  if (!canManage(user.role, module)) return html(errorPage('Akses ditolak', 'Role Anda tidak memiliki izin untuk tindakan ini.'), 403);
  if (module === 'konten') return savePageContent(request, env, url, user);
  if (module === 'media' && parts[2] === 'upload') return uploadMedia(request, env, url, user);
  if (module === 'media' && parts[2]) return parts[3] === 'delete' ? deleteMedia(env, url, user, parts[2]) : updateMedia(request, env, url, user, parts[2]);
  if (module === 'pesan-masuk' && parts[3] === 'status') return updateInquiry(request, env, url, user, parts[2]);
  if (module === 'pengaturan') return saveSettings(request, env, url, user);
  if (module === 'pengguna') return parts[2] ? updateUser(request, env, url, user, parts[2]) : createUser(request, env, url, user);
  const kind = contentRoutes[module]; if (kind) return saveContent(request, env, url, user, kind, parts[2], parts[3]);
  return html(errorPage('Aksi tidak ditemukan', 'Tindakan admin ini tidak tersedia.'), 404);
}
function sameOrigin(request: Request, url: URL) { const value = request.headers.get('Origin') ?? request.headers.get('Referer'); if (!value) return true; try { return new URL(value).origin === url.origin; } catch { return false; } }
async function savePageContent(request: Request, env: RuntimeEnv, url: URL, user: User) { const form = await request.formData(); const key = clean(form.get('key'), 80); const allowed = new Set(['hero','about','services_home','projects_home','why_hd','process','final_cta']); if (!allowed.has(key)) return html(errorPage('Section tidak valid', 'Pilih section homepage yang tersedia.'), 422); const heading = clean(form.get('heading'), 180); const body = clean(form.get('body'), 3000); const requiresHeading = ['hero','services_home','projects_home','process','final_cta'].includes(key); if (!body || (requiresHeading && !heading)) return html(errorPage('Konten belum lengkap', 'Lengkapi seluruh field wajib pada section ini.'), 422); const data = JSON.stringify({ eyebrow: clean(form.get('eyebrow'), 80), heading, body, cta_label: clean(form.get('cta_label'), 80), cta_href: clean(form.get('cta_href'), 200) }); const status = clean(form.get('status'), 20) === 'PUBLISHED' ? 'PUBLISHED' : 'DRAFT'; await env.DB.prepare('INSERT INTO page_content (key,data,status,active,updated_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET data=excluded.data,status=excluded.status,active=excluded.active,updated_at=CURRENT_TIMESTAMP').bind(key,data,status,form.get('active') ? 1 : 0).run(); await audit(env,user.id,'UPDATE','PAGE_CONTENT',key,`Memperbarui section ${key}`); return redirect(new URL(`/admin/konten?section=${key}`,url)); }
async function saveContent(request: Request, env: RuntimeEnv, url: URL, user: User, kind: ContentKind, id?: string, action?: string) { const form = await request.formData(); const itemId = clean(form.get('id')) || id; if (action === 'delete' && itemId) { await env.DB.prepare("UPDATE content_items SET status = 'ARCHIVED', updated_at = CURRENT_TIMESTAMP WHERE id = ? AND kind = ?").bind(itemId, kind).run(); await audit(env,user.id,'ARCHIVE',kind,itemId,'Konten diarsipkan'); return redirect(new URL(`/admin/${routeFor(kind)}`,url)); } const title = clean(form.get('title'), 180), slug = clean(form.get('slug'), 120); if (!title || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return html(errorPage('Data belum valid', 'Judul wajib diisi dan slug harus memakai huruf kecil, angka, serta tanda hubung.'),422); const data = JSON.stringify(Object.fromEntries(extraFields[kind].map(field => [field.key, clean(form.get(`meta_${field.key}`), 3000)]))); const fields = [title,slug,clean(form.get('category'),80),clean(form.get('summary'),500),clean(form.get('body'),12000),data,clean(form.get('seo_title'),180),clean(form.get('meta_description'),160),clean(form.get('canonical_url'),500),clean(form.get('index_status'),20) || 'INDEX_FOLLOW',clean(form.get('status'),20) || 'DRAFT',form.get('featured') ? 1 : 0]; try { if (itemId) { const previous = await env.DB.prepare('SELECT slug FROM content_items WHERE id = ? AND kind = ?').bind(itemId,kind).first<{slug:string}>(); await env.DB.prepare('UPDATE content_items SET title=?,slug=?,category=?,summary=?,body=?,data=?,seo_title=?,meta_description=?,canonical_url=?,index_status=?,status=?,featured=?,published_at=CASE WHEN ? = \'PUBLISHED\' AND published_at IS NULL THEN CURRENT_TIMESTAMP ELSE published_at END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND kind=?').bind(...fields,fields[10],itemId,kind).run(); if (previous?.slug && previous.slug !== slug) await env.DB.prepare('INSERT INTO redirects (id,from_path,to_path,status_code) VALUES (?,?,?,301) ON CONFLICT(from_path) DO UPDATE SET to_path=excluded.to_path,status_code=301').bind(crypto.randomUUID(),`/${routeFor(kind)}/${previous.slug}`,`/${routeFor(kind)}/${slug}`).run(); await audit(env,user.id,'UPDATE',kind,itemId,`Memperbarui ${title}`); } else { const newId=crypto.randomUUID(); await env.DB.prepare('INSERT INTO content_items (id,kind,title,slug,category,summary,body,data,seo_title,meta_description,canonical_url,index_status,status,featured,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,CASE WHEN ? = \'PUBLISHED\' THEN CURRENT_TIMESTAMP END)').bind(newId,kind,...fields,fields[10]).run(); await audit(env,user.id,'CREATE',kind,newId,`Membuat ${title}`); } } catch { return html(errorPage('Slug sudah digunakan', 'Gunakan slug unik untuk item ini.'),409); } return redirect(new URL(`/admin/${routeFor(kind)}`,url)); }
async function updateInquiry(request: Request, env: RuntimeEnv, url: URL, user: User, id: string) { const form=await request.formData(); const status=clean(form.get('status'),20); if (!['NEW','CONTACTED','QUALIFIED','CLOSED','SPAM'].includes(status)) return html(errorPage('Status tidak valid','Pilih status inquiry yang tersedia.'),422); await env.DB.prepare('UPDATE inquiries SET status=?,internal_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,clean(form.get('internal_note'),3000),id).run(); await audit(env,user.id,'UPDATE_STATUS','INQUIRY',id,`Status inquiry menjadi ${status}`); return Response.redirect(new URL(`/admin/pesan-masuk/${id}`,url),302); }
async function saveSettings(request: Request, env: RuntimeEnv, url: URL, user: User) { const form=await request.formData(); const keys=['company_name','tagline','site_description','phone','email','address','instagram_url','facebook_url','linkedin_url','whatsapp_number','whatsapp_template','site_url','default_title','default_meta_description','ga4_measurement_id','gtm_id']; for (const key of keys) await env.DB.prepare('INSERT INTO site_settings (key,value,updated_at) VALUES (?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(key,clean(form.get(key),500)).run(); await audit(env,user.id,'UPDATE','SETTINGS',null,'Memperbarui pengaturan global'); return redirect(new URL('/admin/pengaturan',url)); }
async function createUser(request: Request, env: RuntimeEnv, url: URL, user: User) { if (user.role !== 'SUPER_ADMIN') return html(errorPage('Akses ditolak','Hanya super admin yang dapat mengelola pengguna.'),403); const form=await request.formData(); const email=clean(form.get('email'),254).toLowerCase(), password=String(form.get('password') ?? ''), role=clean(form.get('role'),20); if (!email || password.length < 12 || !['EDITOR','SUPER_ADMIN'].includes(role)) return html(errorPage('Data pengguna tidak valid','Gunakan email valid, password minimal 12 karakter, dan role yang tersedia.'),422); const result=await passwordHash(password); try { const id=crypto.randomUUID(); await env.DB.prepare('INSERT INTO users (id,name,email,password_hash,password_salt,role) VALUES (?,?,?,?,?,?)').bind(id,clean(form.get('name'),100),email,result.hash,result.salt,role).run(); await audit(env,user.id,'CREATE','USER',id,`Membuat user ${email}`); } catch { return html(errorPage('Email sudah digunakan','Gunakan email admin lain.'),409); } return Response.redirect(new URL('/admin/pengguna',url),302); }
async function updateUser(request: Request, env: RuntimeEnv, url: URL, actor: User, id: string) { if (actor.role !== 'SUPER_ADMIN') return html(errorPage('Akses ditolak','Hanya super admin yang dapat mengelola pengguna.'),403); const target = await env.DB.prepare('SELECT id, role, status FROM users WHERE id = ?').bind(id).first<{id:string;role:Role;status:string}>(); if (!target) return html(errorPage('Pengguna tidak ditemukan','Pengguna yang ingin diubah tidak tersedia.'),404); const form = await request.formData(); const role = clean(form.get('role'),20) as Role, status = clean(form.get('status'),20), password = String(form.get('password') ?? ''); if (!['EDITOR','SUPER_ADMIN'].includes(role) || !['ACTIVE','DISABLED'].includes(status) || (password && password.length < 12)) return html(errorPage('Data pengguna tidak valid','Role/status tidak tersedia atau password kurang dari 12 karakter.'),422); if (!canChangeAdmin(actor,target,role,status)) return html(errorPage('Akses ditolak','Anda tidak dapat menurunkan role atau menonaktifkan akun sendiri.'),403); if (target.role === 'SUPER_ADMIN' && (role !== 'SUPER_ADMIN' || status !== 'ACTIVE')) { const admins = await env.DB.prepare("SELECT COUNT(*) AS total FROM users WHERE role = 'SUPER_ADMIN' AND status = 'ACTIVE'").first<{total:number}>(); if (Number(admins?.total) < 2) return html(errorPage('Aksi ditolak','Setidaknya satu super admin aktif harus tetap tersedia.'),422); } if (password) { const result = await passwordHash(password); await env.DB.prepare('UPDATE users SET role = ?, status = ?, password_hash = ?, password_salt = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').bind(role,status,result.hash,result.salt,id).run(); } else await env.DB.prepare('UPDATE users SET role = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').bind(role,status,id).run(); if (status === 'DISABLED') await env.DB.prepare('DELETE FROM sessions WHERE user_id = ?').bind(id).run(); await audit(env,actor.id,password ? 'RESET_PASSWORD' : 'UPDATE','USER',id,password ? 'Mereset password pengguna' : `Mengubah role/status pengguna menjadi ${role}/${status}`); return redirect(new URL('/admin/pengguna',url)); }

async function uploadMedia(request: Request, env: RuntimeEnv, url: URL, user: User) { const form=await request.formData(); const file=form.get('file'); if (!(file instanceof File)) return html(errorPage('File tidak tersedia','Pilih file yang ingin diupload.'),422); const allowed=new Map([['image/jpeg',10*1024*1024],['image/png',10*1024*1024],['image/webp',10*1024*1024],['image/avif',10*1024*1024],['application/pdf',20*1024*1024]]); if (!allowed.has(file.type) || file.size > allowed.get(file.type)!) return html(errorPage('Upload ditolak','Format atau ukuran file tidak sesuai. Maksimum gambar 10 MB dan PDF 20 MB.'),422); const bytes=new Uint8Array(await file.arrayBuffer()); if (!validMagic(bytes,file.type)) return html(errorPage('Upload ditolak','Isi file tidak sesuai dengan format yang dipilih.'),422); const id=crypto.randomUUID(); const extension=extensionFor(file.type); const objectKey=`media/${id}.${extension}`; await env.MEDIA.put(objectKey,bytes,{httpMetadata:{contentType:file.type,cacheControl:'public, max-age=31536000, immutable'}}); await env.DB.prepare('INSERT INTO media (id,object_key,original_filename,content_type,size,alt,caption,uploader_id) VALUES (?,?,?,?,?,?,?,?)').bind(id,objectKey,clean(file.name,255),file.type,file.size,clean(form.get('alt'),250),clean(form.get('caption'),500),user.id).run(); await audit(env,user.id,'UPLOAD','MEDIA',id,`Mengunggah ${file.name}`); return Response.redirect(new URL('/admin/media',url),302); }
async function updateMedia(request: Request, env: RuntimeEnv, url: URL, user: User, id: string) { const form = await request.formData(); const alt = clean(form.get('alt'),250); if (!alt) return html(errorPage('Alt text wajib', 'Isi alt text yang menjelaskan media.'),422); const result = await env.DB.prepare('UPDATE media SET alt = ?, caption = ? WHERE id = ?').bind(alt,clean(form.get('caption'),500),id).run(); if (!result.meta.changes) return html(errorPage('Media tidak ditemukan','Media yang ingin diperbarui tidak tersedia.'),404); await audit(env,user.id,'UPDATE','MEDIA',id,'Memperbarui metadata media'); return redirect(new URL('/admin/media',url)); }
async function deleteMedia(env: RuntimeEnv, url: URL, user: User, id: string) { const item = await env.DB.prepare('SELECT object_key, original_filename FROM media WHERE id = ?').bind(id).first<{object_key:string;original_filename:string}>(); if (!item) return html(errorPage('Media tidak ditemukan','Media yang ingin dihapus tidak tersedia.'),404); await env.MEDIA.delete(item.object_key); await env.DB.prepare('DELETE FROM media WHERE id = ?').bind(id).run(); await audit(env,user.id,'DELETE','MEDIA',id,`Menghapus ${item.original_filename}`); return redirect(new URL('/admin/media',url)); }
function extensionFor(type: string) { return ({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif','application/pdf':'pdf'} as Record<string,string>)[type] ?? 'bin'; }
function validMagic(bytes: Uint8Array, type: string) { const starts=(...values:number[])=>values.every((value,index)=>bytes[index]===value); if(type==='image/jpeg') return starts(0xff,0xd8,0xff); if(type==='image/png') return starts(0x89,0x50,0x4e,0x47); if(type==='image/webp') return String.fromCharCode(...bytes.slice(0,4))==='RIFF' && String.fromCharCode(...bytes.slice(8,12))==='WEBP'; if(type==='application/pdf') return String.fromCharCode(...bytes.slice(0,4))==='%PDF'; if(type==='image/avif') return String.fromCharCode(...bytes.slice(4,12)).includes('ftyp'); return false; }
async function media(request: Request, env: RuntimeEnv, id: string) { const record=await env.DB.prepare('SELECT object_key,content_type FROM media WHERE id=?').bind(id).first<{object_key:string;content_type:string}>(); if(!record) return new Response('Not found',{status:404}); const object=await env.MEDIA.get(record.object_key); if(!object) return new Response('Not found',{status:404}); const headers=new Headers({'Content-Type':record.content_type,'Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}); object.writeHttpMetadata(headers); return new Response(object.body,{headers}); }

async function api(request: Request, env: RuntimeEnv, url: URL, ctx: ExecutionContext): Promise<Response> { if(url.pathname==='/api/inquiries' && request.method==='POST') return createInquiry(request,env,url,ctx); return Response.json({error:{code:'NOT_FOUND',message:'API tidak ditemukan'}},{status:404,headers:{'X-Content-Type-Options':'nosniff'}}); }
async function createInquiry(request: Request, env: RuntimeEnv, url: URL, ctx: ExecutionContext) { const length=Number(request.headers.get('Content-Length') ?? 0); if(length>32*1024) return html(errorPage('Pesan terlalu besar','Ringkas pesan Anda lalu coba lagi.'),413); const form=await request.formData(); const name=clean(form.get('name'),100),phone=clean(form.get('phone'),50),message=clean(form.get('message'),3000); if(!name||!phone||!message) return html(errorPage('Data belum lengkap','Nama, nomor telepon, dan pesan wajib diisi.'),422); const id=crypto.randomUUID(), reference=`HD-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${id.slice(0,6).toUpperCase()}`; await env.DB.prepare('INSERT INTO inquiries (id,reference,name,phone,service,message,source) VALUES (?,?,?,?,?,?,?)').bind(id,reference,name,phone,clean(form.get('service'),100),message,'website').run(); ctx.waitUntil(audit(env,null,'CREATE','INQUIRY',id,`Inquiry ${reference} diterima`)); return html(publicLayout('Inquiry terkirim','Terima kasih sudah menghubungi HD Karya Bandung.',`<h1>Terima kasih</h1><p>Inquiry Anda telah dicatat dengan referensi <strong>${escape(reference)}</strong>. Tim kami akan menindaklanjuti melalui nomor yang Anda berikan.</p><a class="button button-accent" href="/">Kembali ke beranda</a>`),201); }

function robots(url: URL) { return `User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\n\nSitemap: ${url.origin}/sitemap.xml\n`; }
async function sitemap(url: URL, env: RuntimeEnv) { const rows=await env.DB.prepare("SELECT kind,slug,updated_at FROM content_items WHERE status='PUBLISHED' AND index_status='INDEX_FOLLOW' AND slug IS NOT NULL").all<{kind:ContentKind;slug:string;updated_at:string}>(); const fixed=['/','/tentang-kami','/layanan','/proyek','/galeri','/artikel','/kontak']; const locations=[...fixed.map(path=>({path,lastmod:new Date().toISOString().slice(0,10)})),...rows.results.map(row=>({path:`/${routeFor(row.kind)}/${row.slug}`,lastmod:row.updated_at.slice(0,10)}))]; const xml=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${locations.map(item=>`<url><loc>${escapeXml(url.origin+item.path)}</loc><lastmod>${escapeXml(item.lastmod)}</lastmod></url>`).join('')}</urlset>`; return text(xml,{'Content-Type':'application/xml; charset=utf-8','Cache-Control':'public, max-age=3600'}); }
function escapeXml(value:string) { return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'}[char]!)); }
